spring.application.name=Gestor de Biblioteca

spring.datasource.url=jdbc:sqlserver://localhost:1433;databaseName=Biblioteca;encrypt=false;trustServerCertificate=true
spring.datasource.username=sa
spring.datasource.password=${DATASOURCE_PASSWORD}
spring.datasource.driver-class-name=com.microsoft.sqlserver.jdbc.SQLServerDriver
spring.jpa.hibertane.ddl-auto=update
spring.jpa.show-sql=true

#Configuracion de seguridad
jwt.llave.privada=ksfdvsVDLa5456/6FGFSD/D+DDKJOljdjoso
security.jwt.user.generator=AUTH0JWT-BACKEND